server:
  port: 8081
  servlet:
    context-path: /card-api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardsapi?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-startegy: ant_path_matcher
  flyway:
    url: jdbc:mysql://localhost:3306/cardsapi?useTimezone=true&serverTimezone=America/Sao_Paulo
    user: admin
    password: admin